Docker build env

diff --git a/run b/run
--- a/run
+++ b/run
@@ -3,13 +3,26 @@
 function stop_containers {
   docker stop demo_ps-redis || true
   docker rm demo_ps-redis || true
+  docker stop demo_ps-purerl ||  true
+  docker rm demo_ps-purerl ||  true
 }
 
 stop_containers
 
 docker run --name demo_ps-redis --publish 6379:6379 -d redis
 
-erl -init_debug +sbwt none -pa _build/default/lib/*/ebin _checkouts/*/ebin -boot _build/default/rel/demo_ps/releases/1/demo_ps -config release-files/sys.config
+
+if ! command -v erl &> /dev/null
+then
+  echo "erl not found, launching docker container instead"
+  ./run_docker_image.sh erl -init_debug +sbwt none -pa _build/default/lib/*/ebin _checkouts/*/ebin -boot _build/default/rel/demo_ps/releases/1/demo_ps -config release-files/sys.config
+  exit
+else
+  echo "erl found locally, assuming the environment is good to go"
+  erl -init_debug +sbwt none -pa _build/default/lib/*/ebin _checkouts/*/ebin -boot _build/default/rel/demo_ps/releases/1/demo_ps -config release-files/sys.config
+
+fi
+
 
 stop_containers
 
